version: '2'

services:
  nginx:
    image: "nginx"
    tty: true
    stdin_open: true
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - rgonPasswd:/etc/nginx/htpasswd
      - rgonConf:/etc/nginx/conf.d
      - rgonVhost:/etc/nginx/vhost.d
      - rgonCerts:/etc/nginx/certs:ro
    labels:
      io.rancher.sidekicks: rgon-proxy
      io.rancher.scheduler.global: 'false'  # true for multi-host
      rgon-proxy: nginx
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 5
  rgon-proxy:
    image: "causticlab/rgon-proxy:dev"  # :latest for production
    tty: true
    stdin_open: true
    links:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - rgonRancherGen:/etc/rancher-gen
    links:
      - nginx
    labels:
      io.rancher.scheduler.global: 'false'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
      rgon-proxy: rancher-gen
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 5
    command: "-config /etc/rancher-gen/default/rancher-gen.cfg"
